//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teams
    {
        public int TID { get; set; }
        public string TName { get; set; }
        public int THeader { get; set; }
        public Nullable<int> SchoolID { get; set; }
    }
}
